Controllers/AccountsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Travel_Reimbursement.Models;
using System.Data.SqlClient;
using System.Data;
using Microsoft.AspNetCore.Identity;
using Travel_Reimbursement.ContextDBConfig;
using System.Net.Mail;
using System.Net;
using Microsoft.AspNetCore.Authorization;
using Travel_Reimbursement.ActionFilters;
using Message=System.Console;

namespace Travel_Reimbursement.Controllers;

[Log]
public class AccountsController : Controller
{
    private readonly UserManager<ApplicationUser>? _userManager;
    private readonly SignInManager<ApplicationUser>? _signInManager;
    public AccountsController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
    {
        _userManager = userManager;
        _signInManager = signInManager;
    }

    public IActionResult login()
    {
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> login(LoginModel login, string? returnUrl)
    {
        if(ModelState.IsValid)
        {
            
            var result=await _signInManager.PasswordSignInAsync(login.Email, login.Password,false,false);
            if(result.Succeeded)
            {
                if(!string.IsNullOrEmpty(returnUrl))
                return LocalRedirect(returnUrl);
                return RedirectToAction("Index","Details");
            }
            ModelState.AddModelError("","Invalid Login Attempt");
            
        }
        return View(login);
    }

      [Authorize]
    public async Task<IActionResult> logout()
    {
        await _signInManager.SignOutAsync();
        return RedirectToAction("Index","Home");
    }
     public IActionResult register()
    {
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> register( RegisterModel register)
    {
        if(ModelState.IsValid)
        {
            var user = new ApplicationUser()
            {
                Name=register.Name,
                Email=register.Email,
                UserName=register.Email
            };
            var result = await _userManager.CreateAsync(user,register.Password);
            if(result.Succeeded)
            {
                await _signInManager.PasswordSignInAsync(user, register.Password,false,false);
                return RedirectToAction("Index","Home");
            }
            else
            {
                foreach(var error in result.Errors)
                {
                   // ModelState.AddModelError("",err.Description);
                   Message.WriteLine("",error.Description);
                }
            }
        }
        return View(register);
    }
    

}

Controllers/DetailsController.cs
using Travel_Reimbursement.Models;
using Travel_Reimbursement.Models.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Travel_Reimbursement.ContextDBConfig;
using System.Net.Http.Headers;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using Microsoft.Data.SqlClient;

namespace Travel_Reimbursement.Controllers
{
    public class DetailsController : Controller
    {
        private readonly Travel_ReimbursementDbContext _dbContext;
         
        public DetailsController(Travel_ReimbursementDbContext dbContext)
        {
          
            _dbContext= dbContext;
        }
        [HttpGet]
        [Authorize]
       
        public async Task<IActionResult> index()
        {
            try
            {
                var task=Task.Run(async ()=>
                {
                    var travelTable=await _dbContext.Traveltable.ToListAsync();
                    return travelTable;
                });

                var result=await task;
                return View(result);

            }
            catch(Exception exception)
            {
                ModelState.AddModelError("An error occured.",exception.Message);
                return null;
            }
        }

        [HttpGet]
        public IActionResult create()
        {
            return View();
        }
    
        [HttpPost]
        public async Task<IActionResult> create(AddTravelModel addTravelModel)
        {
            try
                {
                    if(ModelState.IsValid)
                        {
                            if(addTravelModel==null)
                            {
                                throw new ArgumentNullException(nameof(addTravelModel));
                            }
                            if(string.IsNullOrEmpty(addTravelModel.Clientname))
                            {
                                throw new ArgumentException("Name cannot be empty.",nameof(addTravelModel.Clientname));
                            }
                            if(addTravelModel.Clientname=="Admin")
                            {
                                throw new ApplicationException("Cannot create a Client name with the name 'Admin'.");
                            }
                            var employee = new TravelModel()
                            {
                                
                                TravelId=addTravelModel.TravelId,
                                Passportnumber=addTravelModel.Passportnumber,
                                Issue=addTravelModel.Issue,
                                ExpiryDate=addTravelModel.ExpiryDate,
                                Place=addTravelModel.Place,
                                PAN=addTravelModel.PAN,
                                Department=addTravelModel.Department,
                                Project=addTravelModel.Project,
                                Clientname=addTravelModel.Clientname,
                                Country=addTravelModel.Country,
                                Fromdate=addTravelModel.Fromdate,
                                Todate=addTravelModel.Todate,
                                NoofDays=addTravelModel.NoofDays,
                                Perdiem=addTravelModel.Perdiem,
                                Eligible=addTravelModel.Eligible,
                                Date=addTravelModel.Date,
                                Particularofexpenses=addTravelModel.Particularofexpenses,
                                Detailsofexpense=addTravelModel.Detailsofexpense,
                                Currency=addTravelModel.Currency,
                                Amount=addTravelModel.Amount,
                                Mode=addTravelModel.Mode,
                                EmployeeEmail=addTravelModel.EmployeeEmail,
                                Totalperdiem=addTravelModel.Totalperdiem,
                                Totalamount=addTravelModel.Totalamount,
                                Advanceamount=addTravelModel.Advanceamount,
                                Remarks=addTravelModel.Remarks,

                            };
                                await _dbContext.Traveltable.AddAsync(employee);
                                await _dbContext.SaveChangesAsync();
                                return RedirectToAction("index");
           
                        }
                        else
                        {
                            var errorMessage=ModelState.Values.SelectMany(v=>v.Errors).Select(e=>e.ErrorMessage).ToList();
                            TempData["errorMessage"]="Try Again!";
                            return View(addTravelModel);    
                        }
                }
            catch (Exception exception)
            {
                
                ModelState.AddModelError("An error occured.",exception.Message);
            }
            
            return View(addTravelModel);
        }
           
        [HttpGet]
        public async Task<IActionResult> view(int id)
        {
            try
            {
                var employee = await _dbContext.Traveltable.FirstOrDefaultAsync(x=>x.Id==id);
                if(employee!=null)
                {
                    var updateTravelModel=new UpdateTravelModel()
                    {
                    Id=employee.Id,
                    TravelId=employee.TravelId,
                    Passportnumber=employee.Passportnumber, 
                    Issue=employee.Issue,
                    ExpiryDate=employee.ExpiryDate,
                    Place=employee.Place,
                    PAN=employee.PAN,
                    Department=employee.Department,
                    Project=employee.Project,
                    Clientname=employee.Clientname,
                    Country=employee.Country,
                    Fromdate=employee.Fromdate,
                    Todate=employee.Todate,
                    NoofDays=employee.NoofDays,
                    Perdiem=employee.Perdiem,
                    Eligible=employee.Eligible,
                    Date=employee.Date,
                    Particularofexpenses=employee.Particularofexpenses,
                    Detailsofexpense =employee.Detailsofexpense,
                    Currency =employee.Currency,
                    Amount =employee.Amount,
                    Mode =employee.Mode,
                    EmployeeEmail=employee.EmployeeEmail,
                    Totalperdiem =employee.Totalperdiem,
                    Totalamount=employee.Totalamount,
                    Advanceamount=employee.Advanceamount,
                    Remarks=employee.Remarks
                    };
                return await Task.Run(() => View("View",updateTravelModel));
                }
            }
            catch(Exception exception)
                {
                    return View("An error occured.",exception.Message);
                }
                return RedirectToAction("index");  
        }

        [HttpPost]
        public async Task<IActionResult> view(UpdateTravelModel updateTravelModel)
        {  
            try{
            HttpClientHandler clientHandler = new HttpClientHandler();
            clientHandler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; };

            using (var httpClient = new HttpClient(clientHandler))
         {
            httpClient.BaseAddress = new Uri("http://localhost:5029/api/Travel/");
             httpClient.DefaultRequestHeaders.Accept.Clear();
        httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

        HttpResponseMessage response = await httpClient.GetAsync("http://localhost:5029/api/Travel/Get");

        if (response.IsSuccessStatusCode)
        {
            
            var data = response.Content.ReadAsStringAsync().Result;
             
           var employee = JsonConvert.DeserializeObject<List<TravelModel>>(data);
            return View(employee);
        }
        else
        {
            return View("Error");
        }
         
            }
            }
          catch(Exception exception)
                {
                    return View("An error occured.",exception.Message);
                }
    }
 
    

 [HttpPost]
        public async Task<IActionResult> deleteDetails(UpdateTravelModel updateTravelModel)
        {
            try{
             var employee = await _dbContext.Traveltable.FindAsync(updateTravelModel.Id);
            if(employee != null)
            {
                _dbContext.Traveltable.Remove(employee);
                await _dbContext.SaveChangesAsync();
                return RedirectToAction("index");
            }
             return RedirectToAction("Employee is null");
            }
             catch(Exception exception)
                {
                    return View("An error occured.",exception.Message);
                }
           
        }

     


        

    }

    
}

Controllers/FileController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Travel_Reimbursement.ContextDBConfig;
using Travel_Reimbursement.Models;

namespace Travel_Reimbursement.Controllers;

public class FileController : Controller
{
    private readonly Travel_ReimbursementDbContext _context;
    private readonly IWebHostEnvironment _hostEnvironment;

    public FileController(Travel_ReimbursementDbContext context, IWebHostEnvironment hostEnvironment)
    {
        _context = context;
        _hostEnvironment=hostEnvironment;
    }
    
[HttpGet]
  [Authorize]
    public async Task<IActionResult> indexFile()
    {
       try
       {
        var uploadFile=await _context.Filetable.ToListAsync();
        return View(uploadFile);
       }
       catch (Exception exception)
       {
        
        throw new Exception(exception.Message);
       }
      
    }
      public async Task<IActionResult> fileTable(int? id)
      {
        if(id==null)
        {
            return NotFound();
        }
        var fileModel = await _context.Filetable.FirstOrDefaultAsync(m=> m.ImageId == id);
        if(fileModel==null)
        {
            return NotFound();
        }
        return View(fileModel);
      }
      [HttpGet]
      public IActionResult fileUpload()
      {
        return View();
      }
      [HttpPost]
     
      public async Task<IActionResult> fileUpload([Bind("ImageId,Title,ImageFile")] FileModel fileModel)
      {
        if(ModelState.IsValid)
        {
          try{
            string wwwRootPath = _hostEnvironment.WebRootPath;
            string fileName = Path.GetFileNameWithoutExtension(fileModel.ImageFile.FileName);
            string extension = Path.GetExtension(fileModel.ImageFile.FileName);
            fileModel.ImagePath=fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            string path=Path.Combine(wwwRootPath+"/Image/", fileName);
            using (var fileStream = new FileStream(path,FileMode.Create))
            {
                await fileModel.ImageFile.CopyToAsync(fileStream);
            }

            _context.Add(fileModel);
            await _context.SaveChangesAsync();
            return RedirectToAction("IndexFile");

          }
          catch(Exception exception)
                {
                    ModelState.AddModelError(string.Empty,$"Something went wrong {exception.Message}");
                }
            }
           
            return View(fileModel);  
      }
       

     
    

        public async Task<IActionResult> deleteFile(int? id)
        {
          if(id==null)
          {
            return NotFound();
          }
          var fileModel= await _context.Filetable.FirstOrDefaultAsync(m=>m.ImageId==id);
          if(fileModel==null)
          {
            return NotFound();
          }
          return View(fileModel);
        }
        [HttpPost, ActionName("DeleteFile")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> deleteConfirmed(int id)
        {
          try
          {
               var fileModel=await _context.Filetable.FindAsync(id);

          var imagePath=Path.Combine(_hostEnvironment.WebRootPath,"image",fileModel.ImagePath);
          if(System.IO.File.Exists(imagePath))
             System.IO.File.Delete(imagePath);


          _context.Filetable.Remove(fileModel);
          await _context.SaveChangesAsync();
          return RedirectToAction(nameof(indexFile));
          }
          catch (Exception exception)
          {
            
            throw new Exception(exception.Message);
          }
       
        }

        private bool FileModelExists(int id)
        {
          return _context.Filetable.Any(e => e.ImageId==id);
        }
    
}

Views/File/DeleteFile.cshtml
@model Travel_Reimbursement.Models.FileModel
@{
    ViewData["Title"]="DeleteFile";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Travel_Reimbursement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Travel_Reimbursement.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
     <header class="position-sticky top-0">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            
            <div class="container-fluid">
                <a class="navbar-brand fw-bold text-blue" asp-area="" asp-controller="Home" asp-action="Index">Travel_Reimbursement</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                 <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        @* <li class="nav-item">
                            <a class="nav-link fw-bold text-blue" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li> *@
                         <li class="nav-item">
                            <a class="nav-link fw-bold text-blue" asp-area="" asp-controller="Details" asp-action="Index">Details</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link fw-bold text-blue" asp-area="" asp-controller="File" asp-action="IndexFile">FileUpload</a>
                        </li>
                    </ul>
                </div>
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-end" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link fw-bold text-blue" asp-area="" asp-controller="Accounts" asp-action="Logout">Logout</a>
                        </li>
                         
                    </ul>
                </div>
            </div>
        </nav>
     </header>

<h3>Are you sure, you want to delete this?</h3>
<div>
   
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
         <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
         <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
         <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
         <dt class="col-sm-2">
            Uploaded Image
        </dt>
         <dd class="col-sm-10">
            <img decoding="async" src="@("~/image/"+Model.ImagePath)" asp-append-version="true" width="250px" height="250px"/>
        </dd>

    </dl>

    <form asp-action="DeleteFile">
        <input type="hidden" asp-for="ImageId"/>
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="IndexFile">Bact to List</a>
    </form>
</div>
<br>
<br>
<footer class="border-top text-white fixed-bottom">
        <div class="container mt-2">
         <div class="row">
            <div class="col-sm-4 col-md-4 col-lg-4 col-xl-4">
                <h4>Travel Reimbursement</h4>
                <pre>Security</pre>
                <pre>Protection</pre>
                <pre>Saved</pre>
             
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4 col-xl-4">
                <h4>Contact Us</h4>
                <div class="mt-3 mb-2">
                    <span><i class="fa-brands fa-instagram fs-5"></i></span>
                    <span class="fs-6 mx-1"><a href="https://instagram.com/aspire_systems?igshid=YmMyMTA2M2Y= "> Instagram</a></span>
                </div>
                 <div class="mb-2">
                    <span><i class="fa-brands fa-youtube fs-5"></i></span>
                    <span class="fs-6 mx-1"><a href="https://youtube.com/Aspiresys">YouTube</a></span>
                </div>
                 <div class="mb-2"> 
                    <span><i class="fa-brands fa-facebook fs-5"></i></span>
                    <span class="fs-6 mx-1"><a href="https://www.facebook.com/AspireSystems?mibextid=ZbWKwL">Facebook</a></span>
                </div> 
                 <div class="mb-2">
                    <span><i class="fa-regular fa-linkedin fs-5"></i></span>
                    <span class="fs-6 mx-1"><a href="https://www.linkedin.com/company/aspire-systems/">LinkedIn</a></span>
                </div>
                @* <div class="mb-2">
                    <span><i class="fa-regular fa-envelope fs-5"></i></span>
                    <span class="fs-6 mx-1"><a href="mailto:aspiresys@gmail.com"> Mail</a></span>
                </div> *@
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4 col-xl-4">
                <h4>Address</h4>
                <pre>Aspire Systems</pre>
                <pre>Chennai, Siruseri, TamilNadu, India</pre>    
            </div>
         </div>
       <!--  <div>
            <h3  class="text-center">Powered By Gayathri</h3>
         </div>-->
          </div>
    </footer> 
</body>
</html>

Views/File/Fileupload.cshtml
           

@model Travel_Reimbursement.Models.FileModel

 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Travel_Reimbursement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Travel_Reimbursement.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
     <header class="position-sticky top-0">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            
            <div class="container-fluid">
                <a class="navbar-brand fw-bold text-blue" asp-area="" asp-controller="Home" asp-action="Index">Travel_Reimbursement</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                 <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        @* <li class="nav-item">
                            <a class="nav-link fw-bold text-blue" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li> *@
                         <li class="nav-item">
                            <a class="nav-link fw-bold text-blue" asp-area="" asp-controller="Details" asp-action="Index">Details</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link fw-bold text-blue" asp-area="" asp-controller="File" asp-action="IndexFile">FileUpload</a>
                        </li>
                    </ul>
                </div>
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-end" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link fw-bold text-blue" asp-area="" asp-controller="Accounts" asp-action="Logout">Logout</a>
                        </li>
                         
                    </ul>
                </div>
            </div>
        </nav>
     </header>




<h4>File Upload</h4>
<hr />
<div class="row">
    <div class="col-4 d-flex justify-content-center">
       
    <div class="col-md-4">
        <form asp-action="Fileupload" asp-area="File" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="Control-label"></label>
                  @* @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Title, "",new { @class ="text-danger"})
              <span class="text-danger">@TempData["errorTitle"]</span> *@
                <input asp-for="Title" class="form-control"/>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div><br>
             <div class="form-group">
                <label asp-for="ImageFile" class="Control-label"></label>
                  <input asp-for="ImageFile" accept="image/*"/>
            @* @Html.ValidationMessageFor(m => m.ImageFile, "",new { @class ="text-danger"})
              <span class="text-danger">@TempData["errorImageFile"]</span> *@
              <span asp-validation-for="ImageFile" class="text-danger"></span> 
            </div><br>
            <div class="form-group">
                <input type="submit" value="Fileupload" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
</div>
<div>
    <a asp-action="IndexFile">History</a>
</div>
<br>
<br>
<br>
<footer class="border-top text-white fixed-bottom ">
        <div class="container mt-2">
         <div class="row">
            <div class="col-sm-4 col-md-4 col-lg-4 col-xl-4">
                <h4>Travel Reimbursement</h4>
                <pre>Security</pre>
                <pre>Protection</pre>
                <pre>Saved</pre>
             
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4 col-xl-4">
                <h4>Contact Us</h4>
                <div class="mt-3 mb-2">
                    <span><i class="fa-brands fa-instagram fs-5"></i></span>
                    <span class="fs-6 mx-1"><a href="https://instagram.com/aspire_systems?igshid=YmMyMTA2M2Y= "> Instagram</a></span>
                </div>
                 <div class="mb-2">
                    <span><i class="fa-brands fa-youtube fs-5"></i></span>
                    <span class="fs-6 mx-1"><a href="https://youtube.com/Aspiresys">YouTube</a></span>
                </div>
                 <div class="mb-2"> 
                    <span><i class="fa-brands fa-facebook fs-5"></i></span>
                    <span class="fs-6 mx-1"><a href="https://www.facebook.com/AspireSystems?mibextid=ZbWKwL">Facebook</a></span>
                </div> 
                 <div class="mb-2">
                    <span><i class="fa-regular fa-linkedin fs-5"></i></span>
                    <span class="fs-6 mx-1"><a href="https://www.linkedin.com/company/aspire-systems/">LinkedIn</a></span>
                </div>
                @* <div class="mb-2">
                    <span><i class="fa-regular fa-envelope fs-5"></i></span>
                    <span class="fs-6 mx-1"><a href="mailto:aspiresys@gmail.com"> Mail</a></span>
                </div> *@
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4 col-xl-4">
                <h4>Address</h4>
                <pre>Aspire Systems</pre>
                <pre>Chennai, Siruseri, TamilNadu, India</pre>    
            </div>
         </div>
       <!--  <div>
            <h3  class="text-center">Powered By Gayathri</h3>
         </div>-->
          </div>
    </footer> 
</body>
</html>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}