Controllers/DetailsController.cs
using Travel_Reimbursement.Models;
using Travel_Reimbursement.Models.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Travel_Reimbursement.ContextDBConfig;
using System.Net.Http.Headers;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using Microsoft.Data.SqlClient;

namespace Travel_Reimbursement.Controllers
{
    public class DetailsController : Controller
    {
        private readonly Travel_ReimbursementDbContext _dbContext;
         
        public DetailsController(Travel_ReimbursementDbContext dbContext)
        {
          
            _dbContext= dbContext;
        }
        [HttpGet]
        [Authorize]
       
        public async Task<IActionResult> index()
        {
            try
            {
                var task=Task.Run(async ()=>
                {
                    var travelTable=await _dbContext.Traveltable.ToListAsync();
                    return travelTable;
                });

                var result=await task;
                return View(result);

            }
            catch(Exception exception)
            {
                ModelState.AddModelError("An error occured.",exception.Message);
                return null;
            }
        }

        [HttpGet]
        public IActionResult create()
        {
            return View();
        }
    
        [HttpPost]
        public async Task<IActionResult> create(AddTravelModel addTravelModel)
        {
            try
                {
                    if(ModelState.IsValid)
                        {
                            if(addTravelModel==null)
                            {
                                throw new ArgumentNullException(nameof(addTravelModel));
                            }
                            if(string.IsNullOrEmpty(addTravelModel.Clientname))
                            {
                                throw new ArgumentException("Name cannot be empty.",nameof(addTravelModel.Clientname));
                            }
                            if(addTravelModel.Clientname=="Admin")
                            {
                                throw new ApplicationException("Cannot create a Client name with the name 'Admin'.");
                            }
                            var employee = new TravelModel()
                            {
                                
                                TravelId=addTravelModel.TravelId,
                                Passportnumber=addTravelModel.Passportnumber,
                                Issue=addTravelModel.Issue,
                                ExpiryDate=addTravelModel.ExpiryDate,
                                Place=addTravelModel.Place,
                                PAN=addTravelModel.PAN,
                                Department=addTravelModel.Department,
                                Project=addTravelModel.Project,
                                Clientname=addTravelModel.Clientname,
                                Country=addTravelModel.Country,
                                Fromdate=addTravelModel.Fromdate,
                                Todate=addTravelModel.Todate,
                                NoofDays=addTravelModel.NoofDays,
                                Perdiem=addTravelModel.Perdiem,
                                Eligible=addTravelModel.Eligible,
                                Date=addTravelModel.Date,
                                Particularofexpenses=addTravelModel.Particularofexpenses,
                                Detailsofexpense=addTravelModel.Detailsofexpense,
                                Currency=addTravelModel.Currency,
                                Amount=addTravelModel.Amount,
                                Mode=addTravelModel.Mode,
                                EmployeeEmail=addTravelModel.EmployeeEmail,
                                Totalperdiem=addTravelModel.Totalperdiem,
                                Totalamount=addTravelModel.Totalamount,
                                Advanceamount=addTravelModel.Advanceamount,
                                Remarks=addTravelModel.Remarks,

                            };
                                await _dbContext.Traveltable.AddAsync(employee);
                                await _dbContext.SaveChangesAsync();
                                return RedirectToAction("index");
           
                        }
                        else
                        {
                            var errorMessage=ModelState.Values.SelectMany(v=>v.Errors).Select(e=>e.ErrorMessage).ToList();
                            TempData["errorMessage"]="Try Again!";
                            return View(addTravelModel);    
                        }
                }
            catch (Exception exception)
            {
                
                ModelState.AddModelError("An error occured.",exception.Message);
            }
            
            return View(addTravelModel);
        }
           
        [HttpGet]
        public async Task<IActionResult> view(int id)
        {
            try
            {
                var employee = await _dbContext.Traveltable.FirstOrDefaultAsync(x=>x.Id==id);
                if(employee!=null)
                {
                    var updateTravelModel=new UpdateTravelModel()
                    {
                    Id=employee.Id,
                    TravelId=employee.TravelId,
                    Passportnumber=employee.Passportnumber, 
                    Issue=employee.Issue,
                    ExpiryDate=employee.ExpiryDate,
                    Place=employee.Place,
                    PAN=employee.PAN,
                    Department=employee.Department,
                    Project=employee.Project,
                    Clientname=employee.Clientname,
                    Country=employee.Country,
                    Fromdate=employee.Fromdate,
                    Todate=employee.Todate,
                    NoofDays=employee.NoofDays,
                    Perdiem=employee.Perdiem,
                    Eligible=employee.Eligible,
                    Date=employee.Date,
                    Particularofexpenses=employee.Particularofexpenses,
                    Detailsofexpense =employee.Detailsofexpense,
                    Currency =employee.Currency,
                    Amount =employee.Amount,
                    Mode =employee.Mode,
                    EmployeeEmail=employee.EmployeeEmail,
                    Totalperdiem =employee.Totalperdiem,
                    Totalamount=employee.Totalamount,
                    Advanceamount=employee.Advanceamount,
                    Remarks=employee.Remarks
                    };
                return await Task.Run(() => View("View",updateTravelModel));
                }
            }
            catch(Exception exception)
                {
                    return View("An error occured.",exception.Message);
                }
                return RedirectToAction("index");  
        }

        [HttpPost]
        public async Task<IActionResult> view(UpdateTravelModel updateTravelModel)
        {  
            try{
            HttpClientHandler clientHandler = new HttpClientHandler();
            clientHandler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; };

            using (var httpClient = new HttpClient(clientHandler))
         {
            httpClient.BaseAddress = new Uri("http://localhost:5029/api/Travel/");
             httpClient.DefaultRequestHeaders.Accept.Clear();
        httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

        HttpResponseMessage response = await httpClient.GetAsync("http://localhost:5029/api/Travel/Get");

        if (response.IsSuccessStatusCode)
        {
            
            var data = response.Content.ReadAsStringAsync().Result;
             
           var employee = JsonConvert.DeserializeObject<List<TravelModel>>(data);
            return View(employee);
        }
        else
        {
            return View("Error");
        }
         
            }
            }
          catch(Exception exception)
                {
                    return View("An error occured.",exception.Message);
                }
    }
 
    

 [HttpPost]
        public async Task<IActionResult> deleteDetails(UpdateTravelModel updateTravelModel)
        {
            try{
             var employee = await _dbContext.Traveltable.FindAsync(updateTravelModel.Id);
            if(employee != null)
            {
                _dbContext.Traveltable.Remove(employee);
                await _dbContext.SaveChangesAsync();
                return RedirectToAction("index");
            }
             return RedirectToAction("Employee is null");
            }
             catch(Exception exception)
                {
                    return View("An error occured.",exception.Message);
                }
           
        }

     


        

    }

    
}

Controllers/FileController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Travel_Reimbursement.ContextDBConfig;
using Travel_Reimbursement.Models;

namespace Travel_Reimbursement.Controllers;

public class FileController : Controller
{
    private readonly Travel_ReimbursementDbContext _context;
    private readonly IWebHostEnvironment _hostEnvironment;

    public FileController(Travel_ReimbursementDbContext context, IWebHostEnvironment hostEnvironment)
    {
        _context = context;
        _hostEnvironment=hostEnvironment;
    }
    
[HttpGet]
  [Authorize]
    public async Task<IActionResult> indexFile()
    {
       try
       {
        var uploadFile=await _context.Filetable.ToListAsync();
        return View(uploadFile);
       }
       catch (Exception exception)
       {
        
        throw new Exception(exception.Message);
       }
      
    }
      public async Task<IActionResult> fileTable(int? id)
      {
        if(id==null)
        {
            return NotFound();
        }
        var fileModel = await _context.Filetable.FirstOrDefaultAsync(m=> m.ImageId == id);
        if(fileModel==null)
        {
            return NotFound();
        }
        return View(fileModel);
      }
      [HttpGet]
      public IActionResult fileUpload()
      {
        return View();
      }
      [HttpPost]
     
      public async Task<IActionResult> fileUpload([Bind("ImageId,Title,ImageFile")] FileModel fileModel)
      {
        if(ModelState.IsValid)
        {
          try{
            string wwwRootPath = _hostEnvironment.WebRootPath;
            string fileName = Path.GetFileNameWithoutExtension(fileModel.ImageFile.FileName);
            string extension = Path.GetExtension(fileModel.ImageFile.FileName);
            fileModel.ImagePath=fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            string path=Path.Combine(wwwRootPath+"/Image/", fileName);
            using (var fileStream = new FileStream(path,FileMode.Create))
            {
                await fileModel.ImageFile.CopyToAsync(fileStream);
            }

            _context.Add(fileModel);
            await _context.SaveChangesAsync();
            return RedirectToAction("IndexFile");

          }
          catch(Exception exception)
                {
                    ModelState.AddModelError(string.Empty,$"Something went wrong {exception.Message}");
                }
            }
           
            return View(fileModel);  
      }
       

     
    

        public async Task<IActionResult> deleteFile(int? id)
        {
          if(id==null)
          {
            return NotFound();
          }
          var fileModel= await _context.Filetable.FirstOrDefaultAsync(m=>m.ImageId==id);
          if(fileModel==null)
          {
            return NotFound();
          }
          return View(fileModel);
        }
        [HttpPost, ActionName("DeleteFile")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> deleteConfirmed(int id)
        {
          try
          {
               var fileModel=await _context.Filetable.FindAsync(id);

          var imagePath=Path.Combine(_hostEnvironment.WebRootPath,"image",fileModel.ImagePath);
          if(System.IO.File.Exists(imagePath))
             System.IO.File.Delete(imagePath);


          _context.Filetable.Remove(fileModel);
          await _context.SaveChangesAsync();
          return RedirectToAction(nameof(indexFile));
          }
          catch (Exception exception)
          {
            
            throw new Exception(exception.Message);
          }
       
        }

        private bool FileModelExists(int id)
        {
          return _context.Filetable.Any(e => e.ImageId==id);
        }
    
}

Views/ManagerAccount/Approve.cshtml
  @model Travel_Reimbursement.Models.Domain.TravelModel
 
  @* <form method="post" asp-action="Approve" asp-area="ManagerAccount"> 
                            <input type="hidden" asp-for="Id">
                            <div class="form-group">
                                <button type="submit" align="center" class="btn btn-primary rounded submit p-2 px-3" >Submit</button>
                            </div>
                        </form>  *@
                       <h1>Successfully sent, that Travel details were Approved</h1> 

Views/ManagerAccount/Decline.cshtml
@model Travel_Reimbursement.Models.Domain.TravelModel
 
  @* <form method="post" asp-action="Decline" asp-area="ManagerAccount">
                            <input type="hidden" asp-for="Id">
                            <div class="form-group">
                                <button type="submit" align="center" class="btn btn-primary rounded submit p-2 px-3" >Submit</button>
                            </div>
                        </form>  *@
                         <h1>Successfully sent, that Travel details were Declined </h1> 

Views/ManagerAccount/Index.cshtml
@model List<Travel_Reimbursement.Models.Domain.TravelModel>

    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Travel_Reimbursement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Travel_Reimbursement.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
     <header class="position-sticky top-0">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            
            <div class="container-fluid">
                <a class="navbar-brand fw-bold text-blue" asp-area="" asp-controller="Home" asp-action="Index">Travel_Reimbursement</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                 <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        @* <li class="nav-item">
                            <a class="nav-link fw-bold text-blue" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li> *@
                         <li class="nav-item">
                            <a class="nav-link fw-bold text-blue" asp-area="" asp-controller="ManagerAccount" asp-action="Index">EmployeesDetails</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link fw-bold text-blue" asp-area="" asp-controller="ManagerAccount" asp-action="IndexFile">Proof</a>
                        </li>
                    </ul>
                </div>
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-end" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link fw-bold text-blue" asp-area="" asp-controller="ManagerAccount" asp-action="LogoutManager">Logout</a>
                        </li>
                         
                    </ul>
                </div>
            </div>
        </nav>
     </header>


         @* <div class="mt-4 col-md-12 text-center">
            <a class="btn btn-outline-primary btn-rounded "asp-action="Create" asp-controller="Details"
              style="border-radius: 15px;padding-left: 50px;padding-right: 50px;margin: 10px;">Enter the details</a>
         </div> *@
       <!-- <a asp-action="Create" asp-controller="Details" class="btn btn-success">Create</a>-->
   
<h1>Uploaded Details</h1>
        <table class="table">
            <thead  class="text-info bg-dark">
                <tr>
                    <td>Id</td>
                    <td>Department</td>
                    <td>Project</td>
                    <td>Country</td>
                    <td>Eligible</td>
                    <td>Fromdate</td>
                    <td>Todate</td>
                    <td>Date  </td>   
                    <td>Mode</td>
                    <td>Totalamount </td>
                    <td>Manage</td>
                    
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model)
                {
                    <tr>
                    <td>@item.Id</td>
                     <td>@item.Department</td>
                      <td>@item.Project</td>
                      <td>@item.Country</td>
                      <td>@item.Eligible</td>
                     <td>@item.Fromdate  </td>
                      <td>@item.Todate  </td>
                       <td>@item.Date  </td>
                   <td>@item.Mode</td>
                    <td>@item.Totalamount </td>      
                    <td><a class="btn btn-primary btn-sm" href="ManagerAccount/View/@item.Id">View</a></td>

                     @* <td>
                        <a type="submit" class="btn btn-success btn-sm" asp-action="Approve" asp-controller="ManagerAccount">Accept</a>
                         <a type="submit" class="btn btn-danger btn-sm" asp-action="Decline" asp-controller="ManagerAccount">Decline</a>
                    </td> *@
                    @* <button type="submit" class="btn btn-primary" asp-action="Approve" asp-controller="ManagerAccount">Approve</button>
          <button type="submit" class="btn btn-primary" asp-action="Decline" asp-controller="ManagerAccount">Decline</button> *@
                    
                    </tr>
                }
            </tbody>

        </table>
       <footer class="border-top text-white fixed-bottom ">
        <div class="container mt-2">
         <div class="row">
            <div class="col-sm-4 col-md-4 col-lg-4 col-xl-4">
                <h4>Travel Reimbursement</h4>
                <pre>Security</pre>
                <pre>Protection</pre>
                <pre>Saved</pre>
             
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4 col-xl-4">
                <h4>Contact Us</h4>
                <div class="mt-3 mb-2">
                    <span><i class="fa-brands fa-instagram fs-5"></i></span>
                    <span class="fs-6 mx-1"><a href="https://instagram.com/aspire_systems?igshid=YmMyMTA2M2Y= "> Instagram</a></span>
                </div>
                 <div class="mb-2">
                    <span><i class="fa-brands fa-youtube fs-5"></i></span>
                    <span class="fs-6 mx-1"><a href="https://youtube.com/Aspiresys">YouTube</a></span>
                </div>
                 <div class="mb-2"> 
                    <span><i class="fa-brands fa-facebook fs-5"></i></span>
                    <span class="fs-6 mx-1"><a href="https://www.facebook.com/AspireSystems?mibextid=ZbWKwL">Facebook</a></span>
                </div> 
                 <div class="mb-2">
                    <span><i class="fa-regular fa-linkedin fs-5"></i></span>
                    <span class="fs-6 mx-1"><a href="https://www.linkedin.com/company/aspire-systems/">LinkedIn</a></span>
                </div>
                @* <div class="mb-2">
                    <span><i class="fa-regular fa-envelope fs-5"></i></span>
                    <span class="fs-6 mx-1"><a href="mailto:aspiresys@gmail.com"> Mail</a></span>
                </div> *@
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4 col-xl-4">
                <h4>Address</h4>
                <pre>Aspire Systems</pre>
                <pre>Chennai, Siruseri, TamilNadu, India</pre>    
            </div>
         </div>
       <!--  <div>
            <h3  class="text-center">Powered By Gayathri</h3>
         </div>-->
          </div>
    </footer> 
</body>
</html>
    

Views/ManagerAccount/IndexFile.cshtml
@model List<Travel_Reimbursement.Models.FileModel>

   
    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Travel_Reimbursement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Travel_Reimbursement.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
     <header class="position-sticky top-0">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            
            <div class="container-fluid">
                <a class="navbar-brand fw-bold text-blue" asp-area="" asp-controller="Home" asp-action="Index">Travel_Reimbursement</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                 <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        @* <li class="nav-item">
                            <a class="nav-link fw-bold text-blue" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li> *@
                         <li class="nav-item">
                            <a class="nav-link fw-bold text-blue" asp-area="" asp-controller="ManagerAccount" asp-action="Index">EmployeesDetails</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link fw-bold text-blue" asp-area="" asp-controller="ManagerAccount" asp-action="IndexFile">Proof</a>
                        </li>
                    </ul>
                </div>
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-end" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link fw-bold text-blue" asp-area="" asp-controller="ManagerAccount" asp-action="LogoutManager">Logout</a>
                        </li>
                         
                    </ul>
                </div>
                 
            </div>
        </nav>
     </header>

<!--<div class="row">
    <div class="col-md-12">
        <a asp-action="Fileupload" asp-controller="File" class="btn btn-success">Create</a>
    </div>
</div>-->
 @* <div class="mt-4 col-md-12 text-center">
   <a class="btn btn-outline-primary btn-rounded "asp-action="FileUpload" asp-controller="File"
   style="border-radius: 15px;padding-left: 50px;padding-right: 50px;margin: 10px;">Upload the File</a>
             
</div> *@

<div class="row">
    <div class="col-md-12">
        <table class="table">
            <thead  class="text-info bg-dark">
                <tr>
                    
                    <td>Title</td>
                    <td>ImagePath</td>
                     <td>Manage</td> 
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model)
                {
                    <tr>
                     
                        <td>@item.Title</td>
                        <td>@item.ImagePath</td> 
                          <td>
                          <!--  <a asp-action="Edit" asp-controller="Upload" asp-route-id="@item.ImageId">Edit</a>-->
                            <a class="btn btn-primary btn-sm"asp-action="DeleteFile" asp-controller="ManagerAccount" asp-route-id="@item.ImageId">View</a>
                        </td>  
                    </tr>
                }
            </tbody>

        </table>
    </div>
</div>
<footer class="border-top text-white fixed-bottom">
        <div class="container mt-2">
         <div class="row">
            <div class="col-sm-4 col-md-4 col-lg-4 col-xl-4">
                <h4>Travel Reimbursement</h4>
                <pre>Security</pre>
                <pre>Protection</pre>
                <pre>Saved</pre>
             
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4 col-xl-4">
                <h4>Contact Us</h4>
                <div class="mt-3 mb-2">
                    <span><i class="fa-brands fa-instagram fs-5"></i></span>
                    <span class="fs-6 mx-1"><a href="https://instagram.com/aspire_systems?igshid=YmMyMTA2M2Y= "> Instagram</a></span>
                </div>
                 <div class="mb-2">
                    <span><i class="fa-brands fa-youtube fs-5"></i></span>
                    <span class="fs-6 mx-1"><a href="https://youtube.com/Aspiresys">YouTube</a></span>
                </div>
                 <div class="mb-2"> 
                    <span><i class="fa-brands fa-facebook fs-5"></i></span>
                    <span class="fs-6 mx-1"><a href="https://www.facebook.com/AspireSystems?mibextid=ZbWKwL">Facebook</a></span>
                </div> 
                 <div class="mb-2">
                    <span><i class="fa-regular fa-linkedin fs-5"></i></span>
                    <span class="fs-6 mx-1"><a href="https://www.linkedin.com/company/aspire-systems/">LinkedIn</a></span>
                </div>
                @* <div class="mb-2">
                    <span><i class="fa-regular fa-envelope fs-5"></i></span>
                    <span class="fs-6 mx-1"><a href="mailto:aspiresys@gmail.com"> Mail</a></span>
                </div> *@
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4 col-xl-4">
                <h4>Address</h4>
                <pre>Aspire Systems</pre>
                <pre>Chennai, Siruseri, TamilNadu, India</pre>    
            </div>
         </div>
       <!--  <div>
            <h3  class="text-center">Powered By Gayathri</h3>
         </div>-->
          </div>
    </footer> 
</body>
</html>